version: "2.1"

services:
  locator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    environment:
    entrypoint:
      - java
      - -Dlogging.config=classpath:/logging-config.xml
      - -jar
      - /locator.jar
